/*
 * Copyright 2012 Keith Flanagan
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * File created: 28-Aug-2012, 15:44:46
 */

package uk.ac.ncl.aries.entanglement.revlog.commands;

import java.util.logging.Logger;

/**
 *
 * @author Keith Flanagan
 */
public class CreateEdge
    extends GraphOperation
{
  private static final Logger logger = 
      Logger.getLogger(CreateEdge.class.getName());
  
  /*
   * Edge ID
   */
  private String uid;
  
  /*
   * A user-defined, domain-specific type name for this edge. 
   * eg: CDS, Protein, Organism, etc.
   */
  private String type;
  
  /*
   * IDs of connected nodes
   */
  private String fromUid;
  private String toUid;

  
  

  public CreateEdge()
  {
  }
  
  /**
   * This constructor allows you to create an edge without specifying a unique
   * ID for the edge. A UID will automatically be generated by the server in 
   * this case.
   * 
   * @param edgeType
   * @param fromNodeUid
   * @param toNodeUid 
   */
  public CreateEdge(
      String edgeType,
      String fromNodeUid, String toNodeUid)
  {
    this.type = edgeType;
    this.fromUid = fromNodeUid;
    this.toUid = toNodeUid;
  }
  
  
  public CreateEdge(
      String edgeType, String uniqueId, 
      String fromNodeUid, String toNodeUid)
  {
    this.uid = uniqueId;
    this.type = edgeType;
    this.fromUid = fromNodeUid;
    this.toUid = toNodeUid;
  }

  @Override
  public String toString()
  {
    return "CreateEdge{"
        + ", edgeType=" + type + ", uniqueId=" + uid 
        + ", fromNodeUid=" + fromUid + ", toNodeUid=" + toUid + '}';
  }

  public String getUid()
  {
    return uid;
  }

  public void setUid(String uniqueId)
  {
    this.uid = uniqueId;
  }

  public String getType()
  {
    return type;
  }

  public void setType(String edgeType)
  {
    this.type = edgeType;
  }

  public String getFromUid()
  {
    return fromUid;
  }

  public void setFromUid(String fromNodeUid)
  {
    this.fromUid = fromNodeUid;
  }

  public String getToUid()
  {
    return toUid;
  }

  public void setToUid(String toNodeUid)
  {
    this.toUid = toNodeUid;
  }
  
}
